'use client';
import {useEffect,useMemo,useRef,useState} from 'react';import {useParams} from 'next/navigation';import {getSupabase} from '../../../lib/supabase';import MediaPreview from '../../../components/MediaPreview';
const uid=()=>globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2);const firstUrl=(t='')=>t.match(/https?:\/\/[^\s]+/i)?.[0]||'';
export default function Room(){const params=useParams(),roomId=String(params.id||'').toUpperCase(),supabase=useMemo(()=>getSupabase(),[]);const[name,setName]=useState(''),[draftName,setDraftName]=useState(''),[messages,setMessages]=useState([]),[text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false);const myId=useRef(''),bottom=useRef(null);
useEffect(()=>{myId.current=localStorage.getItem('linkroom_user_id')||uid();localStorage.setItem('linkroom_user_id',myId.current);const s=localStorage.getItem('linkroom_name')||'';setName(s);setDraftName(s)},[]);
useEffect(()=>{if(!supabase||!roomId)return;let alive=true;supabase.from('messages').select('*').eq('room_id',roomId).order('created_at',{ascending:true}).limit(300).then(({data,error})=>{if(alive){if(error)setError(error.message);else setMessages(data||[])}});const ch=supabase.channel(`room:${roomId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:`room_id=eq.${roomId}`},p=>setMessages(v=>v.some(m=>m.id===p.new.id)?v:[...v,p.new])).subscribe();return()=>{alive=false;supabase.removeChannel(ch)}},[supabase,roomId]);useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages.length]);
const saveName=()=>{const n=draftName.trim().slice(0,30);if(n){localStorage.setItem('linkroom_name',n);setName(n)}};
async function send(){const body=text.trim();if(!body||!name||sending)return;if(!supabase){setError('ระบบแชทยังไม่ได้เชื่อมฐานข้อมูล');return}setSending(true);setError('');setText('');let preview=null;const url=firstUrl(body);if(url)try{preview=await(await fetch('/api/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})})).json()}catch{}const{error}=await supabase.from('messages').insert({room_id:roomId,sender_id:myId.current,sender_name:name,body,preview,original_url:url||null});if(error){setError(error.message);setText(body)}setSending(false)}
return <main className="shell"><header className="header"><div className="headerTitle"><strong>LinkRoom</strong><span>ห้อง {roomId}</span></div><button className="btn btnGhost" onClick={()=>navigator.clipboard.writeText(location.href)}>คัดลอกลิงก์ห้อง</button></header><section className="messages">{!supabase&&<div className="bubble">เว็บพร้อมแล้ว เหลือเชื่อมระบบแชทอีกขั้นเดียว</div>}{messages.length===0&&<div className="empty">ยังไม่มีข้อความ<br/>ลองส่งข้อความหรือแปะลิงก์จาก IG / FB / X</div>}{messages.map(m=><article key={m.id} className={`msg ${m.sender_id===myId.current?'mine':''}`}><div className="name">{m.sender_name}</div><div className="bubble">{m.body}</div>{m.original_url&&<MediaPreview preview={m.preview} originalUrl={m.original_url}/>}</article>)}<div ref={bottom}/></section><div className="composer"><textarea className="field" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="พิมพ์ข้อความ หรือแปะลิงก์ IG / FB / X…"/><button className="btn btnPrimary send" onClick={send}>{sending?'…':'ส่ง'}</button></div>{error&&<div className="error toast">{error}</div>}{!name&&<div className="modal"><div className="modalCard"><h2>ตั้งชื่อก่อนเข้าห้อง</h2><input autoFocus className="field" value={draftName} onChange={e=>setDraftName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&saveName()} placeholder="ชื่อที่เพื่อนจะเห็น"/><button className="btn btnPrimary full top" onClick={saveName}>เข้าห้อง</button><p className="note">ไม่ต้องสมัครสมาชิก</p></div></div>}</main>}
