'use client';
import {useEffect,useRef,useState} from 'react';import {useParams} from 'next/navigation';import MediaPreview from '../../../components/MediaPreview';
const uid=()=>globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2);const firstUrl=(t='')=>t.match(/https?:\/\/[^\s]+/i)?.[0]||'';
const base=process.env.NEXT_PUBLIC_SUPABASE_URL||'';const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';const headers=()=>({apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json'});
export default function Room(){const params=useParams(),roomId=String(params.id||'').toUpperCase();const[name,setName]=useState(''),[draftName,setDraftName]=useState(''),[messages,setMessages]=useState([]),[text,setText]=useState(''),[error,setError]=useState(''),[sending,setSending]=useState(false);const myId=useRef(''),bottom=useRef(null);
useEffect(()=>{myId.current=localStorage.getItem('linkroom_user_id')||uid();localStorage.setItem('linkroom_user_id',myId.current);const s=localStorage.getItem('linkroom_name')||'';setName(s);setDraftName(s)},[]);
useEffect(()=>{if(!base||!key||!roomId){setError('ระบบแชทยังไม่ได้เชื่อมฐานข้อมูล');return}let live=true;async function load(){try{const q=`${base}/rest/v1/messages?room_id=eq.${encodeURIComponent(roomId)}&select=*&order=created_at.asc&limit=300`;const r=await fetch(q,{headers:headers(),cache:'no-store'});if(!r.ok)throw new Error(await r.text());const data=await r.json();if(live)setMessages(data)}catch(e){if(live)setError('โหลดข้อความไม่สำเร็จ')}}load();const timer=setInterval(load,1500);return()=>{live=false;clearInterval(timer)}},[roomId]);useEffect(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),[messages.length]);
const saveName=()=>{const n=draftName.trim().slice(0,30);if(n){localStorage.setItem('linkroom_name',n);setName(n)}};
async function send(){const body=text.trim();if(!body||!name||sending)return;setSending(true);setError('');setText('');try{let preview=null;const url=firstUrl(body);if(url)try{preview=await(await fetch('/api/preview',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})})).json()}catch{}const r=await fetch(`${base}/rest/v1/messages`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify({room_id:roomId,sender_id:myId.current,sender_name:name,body,preview,original_url:url||null})});if(!r.ok)throw new Error(await r.text());const rows=await r.json();if(rows?.[0])setMessages(v=>v.some(m=>m.id===rows[0].id)?v:[...v,rows[0]])}catch(e){setError('ส่งข้อความไม่สำเร็จ');setText(body)}finally{setSending(false)}}
return <main className="shell"><header className="header"><div className="headerTitle"><strong>LinkRoom</strong><span>ห้อง {roomId}</span></div><button className="btn btnGhost" onClick={()=>navigator.clipboard.writeText(location.href)}>คัดลอกลิงก์ห้อง</button></header><section className="messages">{messages.length===0&&<div className="empty">ยังไม่มีข้อความ<br/>ลองส่งข้อความหรือแปะลิงก์จาก IG / FB / X</div>}{messages.map(m=><article key={m.id} className={`msg ${m.sender_id===myId.current?'mine':''}`}><div className="name">{m.sender_name}</div><div className="bubble">{m.body}</div>{m.original_url&&<MediaPreview preview={m.preview} originalUrl={m.original_url}/>}</article>)}<div ref={bottom}/></section><div className="composer"><textarea className="field" value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="พิมพ์ข้อความ หรือแปะลิงก์ IG / FB / X…"/><button className="btn btnPrimary send" onClick={send}>{sending?'…':'ส่ง'}</button></div>{error&&<div className="error toast">{error}</div>}{!name&&<div className="modal"><div className="modalCard"><h2>ตั้งชื่อก่อนเข้าห้อง</h2><input autoFocus className="field" value={draftName} onChange={e=>setDraftName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&saveName()} placeholder="ชื่อที่เพื่อนจะเห็น"/><button className="btn btnPrimary full top" onClick={saveName}>เข้าห้อง</button><p className="note">ไม่ต้องสมัครสมาชิก</p></div></div>}</main>}
