import {NextResponse} from 'next/server';

function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
export async function GET(req,{params}){
 const {id}=await params; const room=esc(String(id||'').toUpperCase());
 const url=process.env.NEXT_PUBLIC_SUPABASE_URL||'';
 const key=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||'';
 const html=`<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LinkRoom ${room}</title><style>*{box-sizing:border-box}body{margin:0;background:#090a0d;color:#fff;font-family:system-ui,sans-serif}.wrap{max-width:760px;margin:auto;min-height:100vh;display:flex;flex-direction:column}.head{padding:16px 18px;border-bottom:1px solid #252832;display:flex;justify-content:space-between}.head small{color:#9ca3af}.msgs{flex:1;padding:18px;overflow:auto}.msg{margin:0 0 16px}.who{font-size:12px;color:#9ca3af;margin-bottom:5px}.bubble{display:inline-block;background:#20232c;padding:10px 13px;border-radius:14px;max-width:85%;white-space:pre-wrap;word-break:break-word}.mine{text-align:right}.mine .bubble{background:#3559e0}.composer{position:sticky;bottom:0;background:#0d0f14;border-top:1px solid #252832;padding:12px;display:flex;gap:8px}textarea,input{background:#171a22;color:#fff;border:1px solid #303541;border-radius:12px;padding:12px;font:inherit}textarea{flex:1;resize:none}button{border:0;border-radius:12px;padding:0 18px;background:#5572ff;color:#fff;font-weight:700}.modal{position:fixed;inset:0;background:#000b;display:grid;place-items:center}.card{background:#151821;padding:24px;border-radius:18px;width:min(90%,360px)}.card input{width:100%;margin:12px 0}.card button{height:44px;width:100%}.err{color:#ff9b9b;padding:8px 18px}.empty{color:#777;text-align:center;margin-top:25vh}</style></head><body><div class="wrap"><div class="head"><b>LinkRoom</b><small>ห้อง ${room}</small></div><div id="err" class="err"></div><div id="msgs" class="msgs"><div class="empty">ยังไม่มีข้อความ</div></div><div class="composer"><textarea id="text" rows="2" placeholder="พิมพ์ข้อความ…"></textarea><button id="send">ส่ง</button></div></div><div id="modal" class="modal"><div class="card"><b>ตั้งชื่อก่อนเข้าห้อง</b><input id="name" maxlength="30" placeholder="ชื่อที่เพื่อนจะเห็น"><button id="enter">เข้าห้อง</button></div></div><script>
const BASE=${JSON.stringify(url)},KEY=${JSON.stringify(key)},ROOM=${JSON.stringify(String(id||'').toUpperCase())};let NAME=localStorage.getItem('linkroom_name')||'',ME=localStorage.getItem('linkroom_user_id')||((crypto.randomUUID&&crypto.randomUUID())||Math.random().toString(36).slice(2));localStorage.setItem('linkroom_user_id',ME);const H={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'};const $=x=>document.getElementById(x);if(NAME)$('modal').style.display='none';$('name').value=NAME;$('enter').onclick=()=>{NAME=$('name').value.trim().slice(0,30);if(NAME){localStorage.setItem('linkroom_name',NAME);$('modal').style.display='none'}};function safe(s){const d=document.createElement('div');d.textContent=s||'';return d.innerHTML}async function load(){if(!BASE||!KEY){$('err').textContent='ยังไม่ได้เชื่อมฐานข้อมูล';return}try{const r=await fetch(BASE+'/rest/v1/messages?room_id=eq.'+encodeURIComponent(ROOM)+'&select=*&order=created_at.asc&limit=300',{headers:H});if(!r.ok)throw Error(await r.text());const a=await r.json();$('msgs').innerHTML=a.length?a.map(m=>'<div class="msg '+(m.sender_id===ME?'mine':'')+'"><div class="who">'+safe(m.sender_name)+'</div><div class="bubble">'+safe(m.body)+'</div></div>').join(''):'<div class="empty">ยังไม่มีข้อความ</div>';$('msgs').scrollTop=$('msgs').scrollHeight;$('err').textContent=''}catch(e){$('err').textContent='โหลดข้อความไม่สำเร็จ'}}async function send(){const body=$('text').value.trim();if(!body||!NAME)return;$('send').disabled=true;try{const r=await fetch(BASE+'/rest/v1/messages',{method:'POST',headers:{...H,Prefer:'return=minimal'},body:JSON.stringify({room_id:ROOM,sender_id:ME,sender_name:NAME,body})});if(!r.ok)throw Error(await r.text());$('text').value='';await load()}catch(e){$('err').textContent='ส่งข้อความไม่สำเร็จ'}finally{$('send').disabled=false}}$('send').onclick=send;$('text').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};load();setInterval(load,1500);
</script></body></html>`;
 return new NextResponse(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})
}
